name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      
      - name: Install node-gyp tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build tree-sitter grammar
        run: cd packages/tree-sitter-liftledger && pnpm run build
      
      - name: Run tests
        run: pnpm test